### ISSUE TITLE
fix: compatibility with cobrapy

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#102]
### Description of the issue:
We should include compatibility for cobrapy, so ideally the model can be fully used by python users. In the following what needs to be done:

- [x] **To be able to use the full model:**
  - [x] Solve issue #101 
  - [x] Make sure no field is lost when the model is opened with cobrapy:
    - [x] Metabolites:
      - [X] `id`
      - [X] `name`
      - [X] `formula`
      - [X] `charge`
	  - [x] `annotation`
        - [x] `chebi`
        - [x] `kegg.compound`
    - [x] Reactions:
      - [X] `id`
      - [X] `name`
      - [X] `metabolites` (with stoich coeffs)
      - [X] `lower_bound`
      - [X] `upper_bound`
      - [X] `gene_reaction_rule`
      - [x] `subsystem`
	  - [x] `annotation`
        - [x] `ec-code`
        - [x] `kegg.reaction`	
        - [x] `pmid`
      - [x] `confidence_score`
    - [x] Genes:
      - [X] `id`
      - [x] `name`
    - [X] Compartments
- [ ] **To be able to also contribute:** Make sure the model can go through a full IO cycle without losing any of the fields, and keeping the same order (at least in the `.yml` and `.txt`)

I have crossed out all the fields I could find in the model loaded with cobrapy, but maybe I missed something @Midnighter @phantomas1234? The final of the to-do's is probably the most challenging one, so if it's too hard we can create a separate issue once we address the other points. Suggestions/things I might have forgotten are welcome @edkerk @ChristianLieven @demilappa @simas232 @hongzhonglu 
  
**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by Midnighter** [comment]
As referenced in #101, a lot of the open problems in your list will be addressed by https://github.com/opencobra/cobrapy/pull/685. Being able to round-trip SBML files without loss of information is certainly one of my major goals with the refactor of the SBML parser.

**Comment by BenjaSanchez** [comment]
After the merge of https://github.com/opencobra/cobrapy/pull/685 and most recently #216, now every single field is readable in cobrapy. I have moved the contribution part of this issue to #218, as it requires several changes to the writing logics of both cobrapy and cobratoolbox. This issue will be closed on the next release.
