### ISSUE TITLE
feat: biomass pseudo-reaction requirements

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/yeast-GEM#107]
In the current yeastGEM, it lacks some specific cofactors and metal irons, which need to be added with the improvement of the model coverage when hundreds of new reactions will be added to the yeastGEM.

**Comment by BenjaSanchez** [comment]
@hongzhonglu sounds great! could you list those new requirements here? maybe we can get some help to check if they make sense or not from @SysBioChalmers/yeast

**Comment by BenjaSanchez** [comment]
update: this issue has been addressed in #174 and will be closed on the next release
