### ISSUE TITLE
fix: remove genes not found in S288C annotation

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#129]
### Description of the issue:

I was contacted by @snmendoz who pointed out that 2 of the current genes in the model cannot be found in the annotation of strain S288C, [according to NCBI](https://www.ncbi.nlm.nih.gov/assembly/GCF_000146045.2#/def_asm_Primary_Assembly): `YAR069W-A` and `YHR214W-F`. @hongzhonglu do you see these genes in any of the newly added annotations? If so, are the annotations of those genes publicly available somewhere?

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by hongzhonglu** [comment]
@BenjaSanchez 
These two genes could be found from SGD
https://www.yeastgenome.org/locus/S000125021
https://www.yeastgenome.org/locus/S000029723
They are not belong to S288c, but also for the yeast. These two genes are from iSce926.

**Comment by BenjaSanchez** [comment]
@hongzhonglu should then be removed? We should only keep genes belonging to the strain of the model I think.

**Comment by hongzhonglu** [comment]
@BenjaSanchez  As we discussed in last meeting, the present yeast-GEM will be developed as pan-model of Saccharomyces cerevisiae. The strain specific model will be obtained based on yeast-GEM. In this case, it is OK to include these two genes.

**Comment by edkerk** [comment]
@BenjaSanchez @hongzhonglu The general `yeast-GEM` consensus model should describe one species also due to strain-specific gapfilling and curation, and s288c has been the standard for _S .cerevisiae_ models. We schould schedule a meeting to brainstorm and formalize how to deal with non-S288c genes and reactions, I already have some ideas, and then decide on how to deal with these two genes and similar instances.

**Comment by hongzhonglu** [comment]
@edkerk @BenjaSanchez Great! We are also thinking about it. So when are you free?

**Comment by edkerk** [comment]
During our offline discussion on Monday we decided that `yeast-GEM` should remain S288c-specific, to stick with the long-running consensus that the _S. cerevisiae_ GEMs are based on this strain. So non-S288c genes should be removed from this model.

**Comment by snmendoz** [comment]
Thanks a lot, @edkerk, @BenjaSanchez and @hongzhonglu . Now, my life is easier.
