### ISSUE TITLE
fix: some SBO tests failing in memote

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#136]
### Description of the issue:
From the latest [memote report](https://github.com/SysBioChalmers/yeast-GEM/files/2191823/index_SBO.zip), the following SBO tests are still causing problems:
- [x] Reactions:
  - [x] Wrong scores for metabolic and transport reactions, as most reactions are being detected as transport. Discussed in https://github.com/SysBioChalmers/yeast-GEM/issues/106#issuecomment-391685490
  - [x] No sink reactions detected, even though there are 3.
- [x] Genes: Currently there's no option for saving them with cobratoolbox.

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by ChristianLieven** [comment]
'No sink reactions detected, even though there are 3.' This could be fixed with the latest PR to memote https://github.com/opencobra/memote/pull/470, if not remind me on slack or gitter or the memote issue tracker!

**Comment by BenjaSanchez** [comment]
@ChristianLieven will for sure open corresponding issues in memote, just needed to point them out here as well ;)

**Comment by BenjaSanchez** [comment]
Update: All these issues have been solved for a while (as it can be seen in the [latest memote report](https://github.com/SysBioChalmers/yeast-GEM/files/5629715/index_matlab.zip) in the development branch), after some updates in memote and [this](https://github.com/opencobra/cobratoolbox/pull/1590) addition in cobratoolbox.
