### ISSUE TITLE
feat: MetaNetX IDs from yeast 7.6

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#154]
### Description of the issue:
Now that both `model.metMetaNetXID` and `model.rxnMetaNetXID` are valid fields in our model, we should add all available met and rxn IDs from yeast 7.6, which is present in the [MetaNetX repository](https://www.metanetx.org/cgi-bin/mnxweb/repository) under model id `yeastnet_v7_6`.

**I hereby confirm that I have:**
- [x] Checked that a similar issue does not exist already

**Comment by feiranl** [comment]
Is that possible if I upload a MetaNetX reference database as .mat file?

**Comment by BenjaSanchez** [comment]
@feiranl `.mat` files cannot be added in `devel` or any feature branch as you can see in the `.gitignore` setup: https://github.com/SysBioChalmers/yeast-GEM/blob/devel/.gitignore This to prevent conflicts arising between branches if the file gets modified.
