### ISSUE TITLE
fix: correction of gene relation for transport reactions

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/yeast-GEM#160]
When compared with the gene annotation in database of SGD and uniprot, it could be found that there 
are multiple errors in the gene relations for transport reaction, such as the genes for r_1101, r_1133. Thus, we need to correct them. 
The transport rxn list need to be checked:
r_1101
r_1133
r_1173
r_1183
r_1238

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by BenjaSanchez** [comment]
@hongzhonglu could you provide the entire list of errors here? How many rxns are there in total with issues?

**Comment by hongzhonglu** [comment]
@BenjaSanchez  I am preparing the rxn list with gene errors now. Will put it here when i complete the check.

**Comment by BenjaSanchez** [comment]
@hongzhonglu is this a repetition of issue #171? If so we can close this one

**Comment by hongzhonglu** [comment]
@BenjaSanchez This issue is mainly used to correct the genes relation for transport reactions with gene associations while issue #171 is to add genes for transport reactions without gene associations.
