### ISSUE TITLE
fix: a compartment error in one reaction

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/yeast-GEM#169]
### Description of the issue:
* r_4237 is same to r_4238, as only h2o’s compartment is different.

#### Expected feature/value/output:
* r_4238 should be a reaction which transports Ca(2+) into Golgi.

#### Current feature/value/output:
r_4237 | Calcium-transporting ATPase 2 (EC 3.6.3.8) (Vacuolar Ca(2+)-ATPase) | H2O[v] + Ca(2+)[c] + ATP[v] => H+[v] + phosphate[v] + Ca(2+)[v] + ADP[v] | 3.6.3.8 | YGL006W
-- | -- | -- | -- | --
r_4238 | Calcium-transporting ATPase 2 (EC 3.6.3.8) (Vacuolar Ca(2+)-ATPase) | H2O[c] + Ca(2+)[c] + ATP[v] => H+[v] + phosphate[v] + Ca(2+)[v] + ADP[v] | 3.6.3.8 | YGL167C

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by BenjaSanchez** [comment]
this was corrected in PR #170, this issue will be closed on next release
