### ISSUE TITLE
feat: add gene annotation for transport reactions

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/yeast-GEM#171]
Now there are 1029 transport reactions in total while only 174 transport reactions with gene relation. It is essential to add model genes associations for these transport reactions without gene relation.

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by hongzhonglu** [comment]
@edkerk @BenjaSanchez @feiranl  Now two methods were used to improve the gene coverage in the transport reactions. 

The first one is to find the related gene annotation from TCDB, Uniprot, SGD and Reactome database. 

The second one is to find the gene annotation based on the substrate similarity if no gene annotation from database. For example, with biolog experiments, we added lots of new metabolites,like 'd-glucose 1-phosphate', can we find the gene annotation for this new metabolite based on d-glucose? I am not sure about the second method, thus needing comments from all of you.

**Comment by Hao-Chalmers** [comment]
@hongzhonglu, I think the second method is not good. It's better NOT to assign annotation when there is no enough evidence.

**Comment by hongzhonglu** [comment]
@Hao-Chalmers  Thanks for you comment! It is reasonable to do as you said.

**Comment by edkerk** [comment]
Are there not also plenty of reactions that describe "transport" of lipids between membranes, which strictly doesn't refer to diffusion in the same sense of H<sub>2</sub>O diffusion, but it rather describes budding and merging of vesicles between membranes. Should these have there own label?

**Comment by Hao-Chalmers** [comment]
Good idea @BenjaSanchez. The curation of diffusible metabolites would contribute nicely in resolving this issue. Note that some metabolites could be both freely diffusible and transporter-mediated.

**Comment by BenjaSanchez** [comment]
update: 101 transport rxns have now in `devel` GPRs, after #178. @hongzhonglu are there any plans to increase this number more? Otherwise this issue can be closed on the next release

**Comment by hongzhonglu** [comment]
@BenjaSanchez  Thanks for your summary! Currently we have no plan to further increase this number more. But if we found new evidences, we can update it accordingly.

**Comment by BenjaSanchez** [comment]
@hongzhonglu ok! this issue will then be closed on the next release :)
