### ISSUE TITLE
NGAM removal

### ISSUE THREAD

**Issue by hvdinh16** [SysBioChalmers/yeast-GEM#189]
Hi,

I recently find out that non-growth associated maintenance (NGAM) exists in iMM904 (= 1) and yeast 1 (unknown value) but is absent in yeast 2 (https://sourceforge.net/projects/yeast/). There are no discussions about this in yeast 4 paper (Dobson et. al., 2010, https://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-4-145) and the current yeast 8 also does not contain ATP maintenance reaction to account for NGAM. Are there any reasons for this removal of the NGAM?

Thank you,
Hoang

**Comment by edkerk** [comment]
I can't speculate about previous models, but yeast 8 does have an NGAM reaction: `r_4046`, which is by default fixed to `1`.

**Comment by hvdinh16** [comment]
Thank you. I was searching for "ATP maintenance" and missed seeing it.
