### ISSUE TITLE
fix: chemical formulas field

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#19]
When using http://sbml.org/validator/ on the ecYeast7 sbml file, 50 errors appear of the sort:

_Error (SBML Validation Rule #fbc-20303): The value of attribute 'fbc:chemicalFormula' on the SBML <species> object must be set to a string consisting only of atomic names or user defined compounds and their occurrence. Reference: L3V1 Fbc V2 Section 3.4 Encountered '(' when expecting a capital letter._

so these formulas should be fixed

**Comment by willigott** [comment]
I agree with @edkerk: The parentheses (and the `n`) can probably removed in most cases and would then also allow to check for elemental balances. Currently there are 18 species in the model that show this issue:
```
{'s_0001__91__ce__93__': '(C6H10O5)n',
 's_0002__91__c__93__': '(C6H10O5)n',
 's_0003__91__e__93__': '(C6H10O5)n',
 's_0004__91__ce__93__': 'C12H22O11(C6H10O5)n',
 's_0332__91__er__93__': '(GlcN)1 (Ino(acyl)-P)1 (Man)3 (EtN)2 (P)2',
 's_0414__91__g__93__': 'C38H68N2O27P2(C5H8)n',
 's_0443__91__c__93__': 'C32H58N2O22P2(C5H8)n',
 's_0444__91__g__93__': 'C32H58N2O22P2(C5H8)n',
 's_0509__91__c__93__': 'H2O(C8H13NO5)n',
 's_0510__91__ce__93__': 'H2O(C6H12NO4)n',
 's_0642__91__c__93__': 'C20H36O(C5H8)n',
 's_0643__91__lp__93__': 'C20H36O(C5H8)n',
 's_0644__91__er__93__': 'C26H47O9P(C5H8)n',
 's_0645__91__c__93__': 'C20H37O4P(C5H8)n',
 's_0646__91__er__93__': 'C20H37O4P(C5H8)n',
 's_1098__91__m__93__': 'C12H18N2O4S2R2(C2H2NOR)n',
 's_1184__91__c__93__': 'C36H64N2O17P2(C5H8)n',
 's_1309__91__e__93__': 'H2O(C6H8O6)n'}
```

If we look at `"s_0001__91__ce__93__"`, it appears e.g. in reaction `'r_0005'` with the substrates

`['s_1543__91__c__93__'`]

and products

`['s_0794__91__c__93__', 's_1538__91__c__93__', 's_0001__91__ce__93__']`

If we now check chemical formulas of those species we find:

`'C15H22N2O17P2'`

and

`'H', 'C9H11N2O12P2', '(C6H10O5)n'`

One can easily see that this reaction is only balanced for `n=1`, so one can also just remove `n` and the parentheses from the chemical formula. I guess the same holds for most other compounds listed above.

Exception is probably `'(GlcN)1 (Ino(acyl)-P)1 (Man)3 (EtN)2 (P)2'` which was just pulled from [KEGG](http://www.genome.jp/dbget-bin/www_bget?gl:G13044) I guess.

**Comment by BenjaSanchez** [comment]
PR #111 has been merged: the model in `devel` is now valid SBML. This issue will be closed on the next release. Thank you all!
