### ISSUE TITLE
feat: include glycolipids in biomass

### ISSUE THREAD

**Issue by hvdinh16** [SysBioChalmers/yeast-GEM#191]
Glycolipid (inositol-P-ceramide (IPC), MIPC, or MIP2C) presents in the biomass reaction of yeast 7.6 but not in that of yeast 8.3.3. I wonder why this component(s) are removed.

**Comment by edkerk** [comment]
Since [release 8.1.0](https://github.com/SysBioChalmers/yeast-GEM/releases/tag/v8.1.0), the biomaass composition including lipids are primarily derived from one study. Glycolipids were not reported (which of course doesn't mean that they aren't there, they were just not measured). However, modifying the biomass equation to include these components should result in a functional model.

**Comment by BenjaSanchez** [comment]
this issue will remain open until we find proper sphingolipid measurements to include in the model

**Comment by hongzhonglu** [comment]
Hi @hvdinh16 @edkerk @BenjaSanchez  I think we could add the Glycolipid back based on https://pubmed.ncbi.nlm.nih.gov/16632881/ and http://docsdrive.com/pdfs/ansinet/jbs/2005/253-256.pdf.

**Comment by feiranl** [comment]
@BenjaSanchez  Is that easy to merge those mesuerment using SLIMER?

**Comment by BenjaSanchez** [comment]
@hongzhonglu you would need to see how the measurements in those papers map out to entities in the yeastGEM model (ceramide, IPC, MIPC and MIP2C) and if there is a % to total lipids, to "normalize" to the current lipid content in our model. Also, a distribution of C24/C26 would be required for the SLIMEr formalism.

@feiranl you would have to add those new coefficients to the lipid backbone pseudoreaction, and then use [`scaleAbundancesInModel`](https://github.com/SysBioChalmers/SLIMEr/blob/master/models/scaleAbundancesInModel.m) to guarantee that the acyl chain pseudoreaction adds up to the same amount of mass.

**Comment by edkerk** [comment]
I think @CarlMalina is also looking into this already.

**Comment by edkerk** [comment]
Applying the curations of lipid metabolism from #12, will result in the inclusion of:

- ceramide
- inositol phosphomannosylinositol phosphoceramide
- inositol-P-ceramide
- mannosylinositol phosphorylceramide
- long-chain base (phytosphingosine & spinagine)
- phosphatidate
- diglyceride
- sn-2-acyl-1-lysophosphatidylinositol
- phosphatidylglycerol
- cardiolipin

I will therefore close this Issue and refer to #12 instead for potential further discussion.
