### ISSUE TITLE
Some metabolites don't have ID from Metnetx database

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/yeast-GEM#197]
Some metabolites with kegg or chebiID don't have ID from MetNetx database.

The metabolite list:
--
s_2777_m
s_2778_m
s_2814_erm
s_2858_ce
s_2891_x
s_2892_x
s_2894_x
s_2898_x
s_2899_x
s_2900_x
s_2903_x
s_2905_x
s_2906_x
s_2907_x
s_2911_x
s_2912_x
s_2913_x
s_2920_x
s_2923_x
s_2927_x
s_2930_x
s_2931_x
s_2933_x
s_2936_erm
s_2937_erm
s_2938_erm
s_2941_erm
s_2945_lp
s_2946_lp
s_2947_lp
s_2949_lp
s_2954_erm
s_2956_erm
s_2958_erm
s_2959_erm
s_2960_erm
s_2961_erm
s_2964_lp
s_2965_lp
s_2967_erm
s_2968_erm
s_2969_erm
s_2970_erm
s_2971_erm
s_2972_erm
s_2973_erm
s_2974_erm
s_2975_vm
s_2978_vm
s_2980_vm
s_2981_vm
s_2982_vm
s_2984_vm
s_2985_vm
s_2986_vm
s_2987_vm
s_2988_vm
s_2989_vm
s_2990_vm
s_2991_vm
s_2992_vm
s_2993_gm
s_2996_gm
s_2998_gm
s_2999_gm
s_3000_gm
s_3002_gm
s_3003_gm
s_3004_gm
s_3005_gm
s_3006_gm
s_3007_gm
s_3008_gm
s_3009_gm
s_3010_gm
s_3011_erm
s_3012_erm
s_3016_erm
s_3018_erm
s_3019_erm
s_3021_erm
s_3023_erm
s_3027_erm
s_3028_erm
s_3031_erm
s_3032_erm
s_3037_erm
s_3038_erm
s_3041_erm
s_3042_erm
s_3043_lp
s_3044_lp
s_3045_lp
s_3046_lp
s_3047_lp
s_3049_lp
s_3051_lp
s_3053_lp
s_3054_lp
s_3055_lp
s_3057_lp
s_3058_lp
s_3059_lp
s_3061_lp
s_3063_lp
s_3067_lp
s_3068_lp
s_3071_lp
s_3072_lp
s_3077_lp
s_3078_lp
s_3081_lp
s_3082_lp
s_3085_erm
s_3091_erm
s_3092_mm
s_3097_mm
s_3098_mm
s_3099_mm
s_3101_mm
s_3109_erm
s_3111_erm
s_3112_erm
s_3113_erm
s_3114_erm
s_3115_erm
s_3116_erm
s_3118_erm
s_3120_erm
s_3121_erm
s_3122_erm
s_3123_erm
s_3124_erm
s_3125_erm
s_3128_mm
s_3130_mm
s_3133_mm
s_3134_mm
s_3135_mm
s_3136_mm
s_3137_mm
s_3138_mm
s_3139_mm
s_3140_mm
s_3141_mm
s_3142_mm
s_3143_mm
s_3144_mm
s_3145_gm
s_3148_gm
s_3151_gm
s_3152_gm
s_3153_gm
s_3154_gm
s_3155_gm
s_3156_gm
s_3157_gm
s_3158_gm
s_3159_gm
s_3160_gm
s_3161_gm
s_3162_gm
s_3163_vm
s_3166_vm
s_3169_vm
s_3170_vm
s_3171_vm
s_3172_vm
s_3173_vm
s_3174_vm
s_3175_vm
s_3176_vm
s_3177_vm
s_3178_vm
s_3179_vm
s_3180_vm
s_3181_erm
s_3187_erm
s_3189_erm
s_3191_erm
s_3193_erm
s_3195_erm
s_3197_erm
s_3198_erm
s_3206_erm
s_3207_erm
s_3208_erm
s_3209_erm
s_3210_erm
s_3211_erm
s_3212_erm
s_3213_erm
s_3214_erm
s_3227_mm
s_3230_mm
s_3231_mm
s_3232_mm
s_3233_mm
s_3241_mm
s_3296_mm
s_3298_mm
s_3300_mm
s_3302_mm
s_3304_mm
s_3305_mm
s_3306_mm
s_3307_mm
s_3323_ce
s_3328_ce
s_3330_ce
s_3332_ce
s_3334_ce
s_3336_ce
s_3337_ce
s_3338_ce
s_3340_vm
s_3346_vm
s_3348_vm
s_3350_vm
s_3352_vm
s_3354_vm
s_3355_vm
s_3356_vm
s_3358_gm
s_3364_gm
s_3366_gm
s_3368_gm
s_3370_gm
s_3372_gm
s_3373_gm
s_3374_gm
s_3376_n
s_3380_n
s_3382_n
s_3384_n
s_3386_n
s_3388_n
s_3389_n
s_3390_n
s_3398_vm
s_3399_vm
s_3406_n
s_3414_ce
s_3424_erm
s_3426_erm
s_3427_erm
s_3448_ce
s_3452_ce
s_3454_ce
s_3456_ce
s_3458_ce
s_3460_ce
s_3461_ce
s_3462_ce
s_3465_ce
s_3466_ce
s_3469_ce
s_3470_ce
s_3471_ce
s_3472_ce
s_3473_ce
s_3474_ce
s_3475_ce
s_3476_ce
s_3478_ce
s_3482_ce
s_3484_ce
s_3486_ce
s_3487_ce
s_3488_ce
s_3489_ce
s_3490_ce
s_3491_ce
s_3493_ce
s_3494_ce
s_3497_c
s_3500_c
s_3502_c
s_3504_c
s_3506_c
s_3508_c
s_3509_c
s_3510_c
s_3512_c
s_3513_n
s_3514_n
s_3515_n
s_3516_n
s_3517_n
s_3518_n
s_3519_n
s_3520_n
s_3521_mm
s_3522_mm
s_3523_mm
s_3524_mm
s_3525_mm
s_3526_mm
s_3527_ce
s_3528_ce
s_3529_ce
s_3530_ce
s_3533_ce
s_3534_ce
s_3542_ce
s_3543_ce
s_3545_c
s_3549_c
s_3551_c
s_3553_c
s_3555_c
s_3556_c
s_3557_c
s_3558_c
s_3559_c
s_3566_erm
s_3567_erm
s_3574_gm
s_3575_gm
s_3582_c
s_3590_erm
s_3614_erm
s_3620_vm
s_3628_gm
s_3633_c
s_3634_c
s_3635_c
s_3636_c
s_3637_c
s_3638_c
s_3639_c
s_3641_vm
s_3642_vm
s_3643_vm
s_3644_vm
s_3645_vm
s_3646_vm
s_3647_vm
s_3649_gm
s_3650_gm
s_3651_gm
s_3652_gm
s_3653_gm
s_3654_gm
s_3655_gm
s_3671_lp
s_3672_lp
s_3673_lp
s_3674_lp
s_3675_m
s_3676_m
s_3678_m
s_3679_m
s_3680_m
s_3681_m
s_3682_m
s_3683_m
s_3685_lp
s_3686_lp
s_3688_lp
s_3689_lp
s_3690_lp
s_3691_lp
s_3692_lp
s_3693_lp
s_3695_lp
s_3697_lp
s_3699_lp
s_3701_lp
s_3702_lp
s_3703_lp
s_3704_lp
s_3705_lp
s_3707_lp
s_3708_lp
s_3748_m
s_3757_v
s_3760_c
s_3763_c
s_3768_c
s_3782_c
s_3783_e
s_3795_c
s_3812_m
s_3816_c
s_3817_c
s_3819_n
s_3821_n
s_3832_r
s_3835_c
s_3838_v
s_3840_v
s_3844_x
s_3853_c
s_3879_r
s_3886_r
s_3888_r
s_3889_r
s_3927_c
s_3928_c
s_3941_c
s_3970_c
s_3985_erm
s_3986_gm
s_3988_c
s_3989_r
s_3990_r
s_4000_c
s_4029_m
s_4032_c
s_4033_c
s_4196_g
s_4197_g
s_4198_g
s_4199_e
s_4200_e
s_4201_e
s_4202_e
s_4203_e
s_4204_e

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [ ] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by edkerk** [comment]
Could you please be more specific which metabolites are missing IDs?

**Comment by hongzhonglu** [comment]
Will summarise it later.

**Comment by feiranl** [comment]
Yes, I used the function mapIDsViaMNXref.m to get all MetaNetX ids based on KEGG/ChEBI ids. However, if they get multiple hits, then I didn't put them in the model. I can double check these metabolites mentioned by Hongzhong.
