### ISSUE TITLE
fix: duplicated protein pseudo-metabolite

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#201]
### Description of the issue:

In reaction `r_4239` there is a metabolite `Protein [cytoplasm]` (met id `s_3884`) that is not the same as the `protein [cytoplasm]` (met id `s_3717`) that is used in the biomass pseudo-reaction. Thanks to @ardicdavis for pointing this out.
```
r_4239:
s_0428[c] + s_3884[c] 	<=>	s_0794[c] + s_1583[c] + s_3885[c]
Arg-tRNA(Arg) [cytoplasm] + Protein [cytoplasm]  <=> H+ [cytoplasm] + tRNA(Arg) [cytoplasm] + L-Arginyl-protein [cytoplasm]
```

@feiranl @hongzhonglu I would either change the name of that metabolite to `generic protein [cytoplasm]` to avoid confusion (as the 2 metabolites fulfill different purposes) or remove that reaction entirely (as it is blocked anyways, because no reaction in the model produces `Protein [cytoplasm]` and no reaction consumes `L-Arginyl-protein [cytoplasm]`). What do you think? What is your view regarding generic molecules such as a generic protein? IMO we should try to avoid them entirely, but perhaps this reaction is an exception?

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by feiranl** [comment]
We include this one with different metID in order to don't mess up the biomass rxn. I am okay to delete that rxn.

**Comment by hongzhonglu** [comment]
@BenjaSanchez @feiranl The annotation of the gene related to this reaction can be found in https://www.uniprot.org/uniprot/P16639. Thus the annotation is right. I prefer to keep the reaction and the gene while change the name of that metabolite to generic protein [cytoplasm].
