### ISSUE TITLE
redundant bracket in GPR rules

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/yeast-GEM#202]
### Description of the issue:
* Redundant brackets exist in the `model.rules` 

#### Expected feature/value/output:
*   YGR143W or YPR159W 
*   x(352) | x(903) 

#### Current feature/value/output:
* ( YGR143W or YPR159W  )
* ( x(352) | x(903) )

**I hereby confirm that I have:**
- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by feiranl** [comment]
@BenjaSanchez @edkerk @hongzhonglu  Should we get rid of those redundant brackets?

**Comment by edkerk** [comment]
These redundant brackets can indeed be removed.

**Comment by BenjaSanchez** [comment]
@feiranl this is actually not a problem with the model, as the rules are not stored with any brackets in the `.xml` file:
```xml
        <fbc:geneProductAssociation>
          <fbc:or>
            <fbc:geneProductRef fbc:geneProduct="G_YGR143W"/>
            <fbc:geneProductRef fbc:geneProduct="G_YPR159W"/>
          </fbc:or>
```
so it is instead a redundancy that cobratoolbox introduces, actually in all rules that have more than one gene, not just the one you mention. Note however that if you convert the model to a RAVEN model using `ravenCobraWrapper.m` all those redundant parenthesis go away, see below (left is COBRA, right is RAVEN):

![image](https://user-images.githubusercontent.com/9384349/78653317-3e748180-78c3-11ea-8c3a-2fb195d5ae2e.png)
