### ISSUE TITLE
Newly added duplicate reactions

### ISSUE THREAD

**Issue by hvdinh16** [SysBioChalmers/yeast-GEM#203]
Hi,

In the yeast-GEM 8.3.4, I found the following newer reactions that are potentially duplicates of older reactions (based on numeral order of ID)

r_4235: duplicate of r_0534
r_4236: lumped reaction, duplicate of r_0697 + r_0553
r_4264: potential duplicate of r_0454

**Comment by feiranl** [comment]
Will change soon.

**Comment by BenjaSanchez** [comment]
@hvdinh16 there is already an issue with duplicated reactions in #187, will add these ones to that discussion and close this issue.
