### ISSUE TITLE
model.S not sparse double

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/yeast-GEM#207]
### Description of the issue:
* Right now, model.S is double instead of sparse double. Should fix that.

**I hereby confirm that I have:**
- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by BenjaSanchez** [comment]
@feiranl is this for performance reasons only, or are there any COBRA/RAVEN functions that error because of this format? If only the former, maybe we should first show a performance comparison to see if it's worth it (as having `S` as double makes operations much less verbose)

**Comment by feiranl** [comment]
model.S in our model right now is double, I don't know when this happens, should we changed back to sparse double?

**Comment by BenjaSanchez** [comment]
I'm not familiar with any benefits of having the matrix as sparse (maybe someone can weigh in here). If it is significant, we could try to see how to change it.

**Comment by BenjaSanchez** [comment]
this issue will be closed as it is not an issue with the model, but rather cobratoolbox changing their parsers at some point to load the model with S as a double matrix instead of sparse.
