### ISSUE TITLE
fix: lipid biomass composition

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/yeast-GEM#21]
The expansive description of lipid metabolism is confusing, so I might be wrong in the following. To my understanding, the model doesn't specify a distribution of different FA chain lengths, but demands all FA chains in equal amounts (for majority of lipid metabolism, sterol esters seem specific):

There are all these individual reactions that build up for instance TAG(16:0, 18:1, 18:1).

`oleoyl-CoA[erm] +   diglyceride (1-16:0, 2-18:1)[erm] => coenzyme A[erm] + triglyceride   (1-16:0, 2-18:1, 3-18:1)[erm]`

They use specific acyl-CoAs (so no pooled pseudometabolite), and nowhere in those reactions is there any specification on abundant each fatty acid is. With that in mind, it would be cheapest to make TAG(16:0, 16:1, 16:0), and this is what I actually see when I run FBA and minimize the number of fluxes.

The model has so-called 'ISA' reactions that 'converts' FA-chain specific TAG species into a generic TAG species:

`triglyceride   (1-16:0, 2-18:1, 3-18:1)[erm] => 0.67901 triglyceride[erm]`

I don't understand what these coefficients mean, but they seem to connect to the chain length (e.g. triglyceride (1-18:0, 2-18:1, 3-16:0) gets the same coefficient, even though it has different number of saturations).

These generic lipid species are then used in the lipid pseudoreaction:

`[...] + 0.000206 fatty acid[c] + [...] + 0.000781   triglyceride[c] + 1.5e-05 zymosterol[c] => lipid[c]`

So nowhere along that path is there any specification of distribution of FA chain lengths & saturation, all TAG species are as likely to be made, with some correction for the amount of carbons (but not hydrogens, as the two species mentioned above with similar coefficients do have different molecular weights).

The ISA reactions for fatty acids have no influence in this for two reasons:

`palmitate[c] =>   0.61538 fatty acid[c]`

1: the coefficients are again just representing the number of carbons, not any measured abundance
2: fatty acid[c] is only used in the lipid pseudoreaction to represent free fatty acids, it is not used to be incorporated in any other lipid species.

**Comment by BenjaSanchez** [comment]
update on this: PR #112 fixes this issue by using the newly defined SLIME reactions: lipids are now split into their 2 basic components, backbone and acyl-chains:
```
lipid -> sL backbone + sC1 acyl-chain1 + sC2 acyl-chain2 + ...
```
With this, separate lipid pseudoreactions are defined later for backbones and for acyl-chains. The stoichiometric coefficients are representing molecular weights, as the data used comes in g/gDW.

More info is found on [SysBioChalmers/SLIMEr](https://github.com/SysBioChalmers/SLIMEr). This issue will be closed when the changes are merged to master.
