### ISSUE TITLE
feat: yeast-GEM maps in caffeine platform

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#212]
### Description of the issue:

For improved visualization of the _S. cerevisiae_ model, the files available at [SysBioChalmers/Yeast-maps](https://github.com/SysBioChalmers/Yeast-maps) could be uploaded to https://caffeine.dd-decaf.eu/, a platform for simulating + visualizing GEM predictions. For this, the following should be done:
- [x] Merge #188 (caffeine operates based on bigg ids).
- [x] Upload model to Caffeine.
- [ ] Translate the yeast-GEM maps into Escher format.
- [ ] Upload maps to Caffeine.

**I hereby confirm that I have:**
- [x] Checked that a similar issue does not exist already

**Comment by hongzhonglu** [comment]
The current issue is that the map format from SysBioChalmers/Yeast-maps should be updated to be visualised using caffeine .

**Comment by BenjaSanchez** [comment]
@hongzhonglu were you able to transform the format available in [SysBioChalmers/Yeast-maps](https://github.com/SysBioChalmers/Yeast-maps) to be compatible with Escher? Is there work somewhere with that?

**Comment by hongzhonglu** [comment]
Hi @BenjaSanchez I am not able to transform the format. Niko has done some work as the part of Yeast8 project but we did not get the completed result from him.

**Comment by BenjaSanchez** [comment]
Update on this: The **model** of yeast-GEM (version 8.4.0) is now available in Caffeine. After #224 was merged, I used those I/O functions to create a model with BiGG ids in .json format in [this fork](https://github.com/BenjaSanchez/yeast-GEM/blob/feat/json-file/ModelFiles/json/yeastGEM.json). I uploaded that model as a publicly available model at https://staging.dd-decaf.eu/interactive-map (can be selected from the `S. cerevisiae` model options when a new simulation card is created). For now it should be used with maps from `iMM904`. It works with varying degrees of success: lipid metabolism for instance has very few matches, but below you can see that Glycolisis/PPP matches very nicely 😄

![image](https://user-images.githubusercontent.com/9384349/85277076-1a1c5000-b483-11ea-9567-409fb2365e1a.png)

@feiranl @hongzhonglu feel free to play around with the model (you can try simulating knockouts, adding reactions, changing bounds, etc) and let me know if overall it's working as intended. If so, I can push it to the production line of Caffeine, and modify the readme file of our repo to direct users to this resource for integrated simulation & visualization.

**Comment by feiranl** [comment]
@BenjaSanchez Hi, I tried adding reactions from MNX and adding a reaction manually inputed, changing bounds, and reactions knocking out. Overall, it is great!. But the reaction knocking is circling all the time, even though new simulation result is generated, but it is still responding. Is that a problem?  And there is a small thing in edit bound there, it will become red after you clicking that, even though I didn't input anything. 
![image](https://user-images.githubusercontent.com/32157802/86541151-ec1b1f00-bf0a-11ea-9f0d-72f508f05a6e.png)

**Comment by BenjaSanchez** [comment]
@feiranl thanks for the feedback! those sound like issues with the caffeine platform, not the yeast model, so feel free to document them at https://github.com/DD-DeCaF/caffeine-vue/issues/new

**Comment by BenjaSanchez** [comment]
update: model is now available in the production line of caffeine, at https://caffeine.dd-decaf.eu/interactive-map

**Comment by forxhunter** [comment]
> https://caffeine.dd-decaf.eu/interactive-map

Hi BenjaSanchez, I check the current version of interactive-map again. But I didnt' find the Yeast GEM map you created. Could you please verify that? https://pathways.embl.de/
![image](https://github.com/user-attachments/assets/8dd5145e-845f-4760-992f-4860551c08a4)
And the old link you gave can no long be opened as well.

**Comment by BenjaSanchez** [comment]
@forxhunter the project DD-DeCaF ended a few years ago, and as far as I know the Caffeine tool is currently not maintained, so you will need to look for other visualization options. The map files are available at https://github.com/SysBioChalmers/Yeast-maps, and an interactive version (not sure if up to date) can be accessed at https://metabolicatlas.org/explore/Yeast-GEM/map-viewer (not at https://pathways.embl.de/). Hope this helps :)

PS: Note that I did not create the yeast GEM map; what I did in this issue was to upload the yeast **_model_** to the caffeine platform, so it could be combined with other maps. if you have questions about the map you should ask them in the corresponding repo: https://github.com/SysBioChalmers/Yeast-maps

**Comment by BenjaSanchez** [comment]
As the caffeine platform is not operational anymore, I propose to close this issue :)
