### ISSUE TITLE
fix: misc errors in model

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/yeast-GEM#215]
#### Metabolite annotation mistake:
[CHEBI:29155](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:29155) is incorrectly annotated for `s_0829[lp]: hexadecaprenyl diphosphate` in the model.

#### Gene annotation mistake:

gene [YIL020C](https://www.yeastgenome.org/locus/S000001282) also EC number should not be linked with `r_4042: raffinose [extracellular]  -> D-fructose [extracellular] + melibiose [extracellular]`

#### Annotation update
KEGG rxnID [R01051](https://www.kegg.jp/dbget-bin/www_bget?rn:R01051) should be linked with `r_0969	ATP [cytoplasm] + D-ribose [cytoplasm] 	->	ADP [cytoplasm] + H+ [cytoplasm] + ribose-5-phosphate [cytoplasm] ` 
KEGG rxnID  [R00291](https://www.kegg.jp/dbget-bin/www_bget?rn:R00291) should be linked with `r_1070	UDP-D-glucose [cytoplasm] 	<=>	UDP-D-galactose [cytoplasm]` 
KEGG rxnID  [R00009](https://www.kegg.jp/dbget-bin/www_bget?rn:R00009) should be linked with `r_0255	2 hydrogen peroxide [cytoplasm] 	->	2 H2O [cytoplasm] + oxygen [cytoplasm] 
`

**Comment by BenjaSanchez** [comment]
@feiranl issues in general are for documenting errors in model, so I have changed the description of the issue to reflect that ;)

why have duplicates here with #187?

**Comment by feiranl** [comment]
@BenjaSanchez  Yes, you are correct. maybe remove that one.

**Comment by BenjaSanchez** [comment]
Update: all metabolite/reaction issues here are addressed. Only missing thing is the wrong gene rule for `r_4042`.

**Comment by feiranl** [comment]
@BenjaSanchez  I will do a quick commits soon.
