### ISSUE TITLE
fix: avoid duplicity in gene name storage

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#217]
### Description of the issue:
In PR #216 we are forcing the model to save the `proteins` COBRA field with the same information as `geneNames`, in order to allow both cobratoolbox and cobrapy to load gene names from the xml file. There is now https://github.com/opencobra/cobrapy/issues/950 to address the problem in one of the two solvers. Once it is solve, we can revert the model to avoid this duplicity.

#### Current feature/value/output:
```xml
<fbc:geneProduct metaid="G_YPL078C" fbc:id="G_YPL078C" fbc:name="ATP4" fbc:label="ATP4"/>
```

#### Expected feature/value/output:

The gene name should be uniquely either in `fbc:name` or `fbc:label`, depending on which package adapts to the other.

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Checked that a similar issue does not exist already

**Comment by edkerk** [comment]
Solved in #373
