### ISSUE TITLE
problem with reactions added after gapfilling (PR #185)

### ISSUE THREAD

**Issue by dtmvandenberg** [SysBioChalmers/yeast-GEM#225]
### Description of the issue:
The MetaNetX ID's of reactions r_4601 till r_4628 are in the model.rxnNotes table instead of model.rxnMetaNetXID in the matlab file of version 8.3.5.

#### Expected feature/value/output:
model.rxnNotes: 'NOTES: added after Gapfilling (PR #185)'
model.rxnMetaNetXID: 'MNXR94845'

#### Current feature/value/output:
model.rxnNotes: 'NOTES: added after Gapfilling (PR #185); MNXR94845'
model.rxnMetaNetXID: ''

#### Reproducing these results:
No code needed just check the model after loading the matlab file.

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by BenjaSanchez** [comment]
@dtmvandenberg thanks for bringing this up! we will address it soon in a fix branch. @feiranl do you think this might have happened with any other of the additions?

**Comment by feiranl** [comment]
will fix this. There is an index issue in the original function. However, there are some cases which we do have MNXR IDs in the notes, which is when they are not exactly same with our reactions, so we move the original MNX IDs to the note filed for correctness.

**Comment by feiranl** [comment]
Fix this in the new pull request #226, bigg IDs for those rxns are also updated.
