### ISSUE TITLE
remove authorship/dates from repo

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#227]
For simplicity I think we should remove all authorships/dates from any scripts/notebooks in this repo, as they are not really needed and usually forgotten to update. More discussion at https://github.com/SysBioChalmers/Human-GEM/issues/176

@feiranl @hongzhonglu @edkerk what do you think?

**I hereby confirm that I have:**
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by edkerk** [comment]
Agree :)

**Comment by hongzhonglu** [comment]
Agree :)

**Comment by feiranl** [comment]
Okay.
