### ISSUE TITLE
fix-bug:yeast8.4.1 cannot grow

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/yeast-GEM#242]
### Description of the issue:
* yeast8.4.1 cannot grow while yeast8.4.0 can.

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by feiranl** [comment]
@BenjaSanchez Is that ok that we can include one line code to chech the growth in saveYeastModel to dismiss this kind of bug?

**Comment by BenjaSanchez** [comment]
@feiranl yes that's a great idea! So that it errors and doesn't let you save the model. I can include it, maybe for both aerobic and anaerobic conditions?

Will you look into the source of the error? It was probably some change in #237 (as that was the only PR that modified stoichiometry). Apologies for not catching it in the review.

**Comment by feiranl** [comment]
@BenjaSanchez  it is because ergterol cannot be synthesized due to rxn change of  `r_0241` in #237, where  `Ferrocytochrome b5` cannot be converted back to`Ferricytochrome b5 `, due to the missing links from `NADH[c]` to `NADH[er]` conversion.

`r_0241	14-demethyllanosterol [cytoplasm] + 5 H+ [cytoplasm] + 3 oxygen [cytoplasm] + 6 Ferrocytochrome b5 [endoplasmic reticulum] 	->	4beta-methylzymosterol-4alpha-carboxylic acid [cytoplasm] + 4 H2O [cytoplasm] + 6 Ferricytochrome b5 [endoplasmic reticulum] 
r_4196	NADH [endoplasmic reticulum] + 2 Ferricytochrome b5 [endoplasmic reticulum] 	<=>	H+ [endoplasmic reticulum] + NAD [endoplasmic reticulum] + 2 Ferrocytochrome b5 [endoplasmic reticulum] 
`

**Comment by feiranl** [comment]
@edkerk @BenjaSanchez Should we fix this with adding other transport reactions like those below, or using `NADH[erm]` and `NAD[erm]` directly in the reaction `r_4196`?
r_3533	NAD [cytoplasm] 	<=>	NAD [endoplasmic reticulum membrane] 
r_3532	NADH [cytoplasm] 	<=>	NADH [endoplasmic reticulum membrane]

**Comment by feiranl** [comment]
> @feiranl yes that's a great idea! So that it errors and doesn't let you save the model. I can include it, maybe for both aerobic and anaerobic conditions?
> 
> Will you look into the source of the error? It was probably some change in #237 (as that was the only PR that modified stoichiometry). Apologies for not catching it in the review.

Warning is also ok.

**Comment by edkerk** [comment]
Sloppy from my side, apologies.

Warning would perhaps be preferred, as it would then still write the YML, and TXT files that would make it easier to go through the changes in the model?

@feiranl Nice spotting of the problem and solutions. What about completely localizing `r_4196` to `erm`, as cytochrome b5 is a membrane protein anyway. Then also use `erm`-localized cytochrome b5 in `r_0241`.

**Comment by edkerk** [comment]
Let's push this quickly as 8.4.2 to make sure we distribute a functional model in `master`.

**Comment by feiranl** [comment]
ok. I will commit it today.
