### ISSUE TITLE
What's the expected growth rate of yeast8?

### ISSUE THREAD

**Issue by BeeAnka** [SysBioChalmers/yeast-GEM#275]
Hi, this is not an issue but a small question. I downloaded the yeast-GEM.xml model and would like to 
make sure that everything is fine before I start my analysis. Therefore I would like to confirm the "basic" features amount of reactions, metabolites, genes and growth rate. I found this information for the yeast 7.6 model but not for the yeast8.
Here are my results: reactions: 4058, metabolites: 2742, genes: 1150 and growth rate from cobrapy standard FBA: 0.08374.
It would be really helpful if you could confirm that these properties are correct or tell me if something went wrong during reading the model with cobrapy.

**Comment by edkerk** [comment]
Seems like you've successfully loaded yeast-GEM! I assume it's version 8.5.0?

**Comment by BeeAnka** [comment]
Yes, it's version 8.5.0 and I just wanted to make sure if the growth rate I get via cobrapy FBA is correct? Sorry, if these questions seems a bit stupid, but I'm quiet new to working with this kind of models.

**Comment by edkerk** [comment]
It's indeed the same growth rate as we get in MATLAB via RAVEN or COBRA.
