### ISSUE TITLE
How to used the ID of metabolites correctly in COBRApy?

### ISSUE THREAD

**Issue by LGJee** [SysBioChalmers/yeast-GEM#280]
Hi, I am the beginner of GEMs, I learn the usage of COBRApy through the tutorials in [https://cobrapy.readthedocs.io/en/latest/](url), I encountered a problem when using the model of yeast8.

After executing the following code

```
import code.io as io
model = io.read_yeast_model()
```

The following three codes will **raise AttributeError**

`print(model.metabolites.nadh_c.summary())`
`print(model.metabolites.s_1203_c.summary())`
`print(model.metabolites.s_1203.summary())`

Last but not least, I would be very grateful if you can provide some basic tutorials on Yeast8 or related application cases, thanks!

**Comment by edkerk** [comment]
You can load the model in cobrapy with BiGG-style identifiers:
```python
model = io.read_yeast_model(True)
print(model.metabolites.nadh_c.summary())
```

The _original_ identifiers (in the style of `s_1203[c]`) indeed raises an AttributeError, probably related to the presence of the square brackets.

**Comment by edkerk** [comment]
Also note that the BiGG-style IDs might not be actual BiGG IDs: #282.
There are no tutorials for Yeast8, but this is a great suggestion that we will work on in 2022: #286
