### ISSUE TITLE
reference for irreversible malate dehydrogenase during anaerobic simulation

### ISSUE THREAD

**Issue by mperisin-lallemand** [SysBioChalmers/yeast-GEM#291]
### Description of the issue:
The `anaerobicModel.m` script indicates that malate dehydrogenase (r_0173, r_0714) should be constrained to zero flux:

`%Block oxaloacetate-malate shuttle (not present in anaerobic conditions)
model.lb(strcmp(model.rxns,'r_0713')) = 0; %Mithocondria
model.lb(strcmp(model.rxns,'r_0714')) = 0; %Cytoplasm`

Is there a reference for this observation? 

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by edkerk** [comment]
> The `anaerobicModel.m` script indicates that malate dehydrogenase (r_0173, r_0714) should be constrained to zero flux:
> 

Note that the _lower bound_ is constrained to zero flux, the reactions can still carry a flux of 0 or higher. This seems to have been introduced when yeast7 was expanded to an [enzyme-constrained model](https://doi.org/10.15252/msb.20167411). It seemed necessary for that model to replicate the observed phenotype. See in the Appendix:


![image](https://user-images.githubusercontent.com/7326655/147512665-72341480-9d04-448c-a1a0-76e5e735a45d.png)
![image](https://user-images.githubusercontent.com/7326655/147512689-6047aeeb-9f28-48bb-8db5-64b3d2f5e45f.png)

It is not an ideal situation, to change such reaction bounds specifically for one condition. We should consider whether these reactions should be reversible, and if, they should also be reversible in anaerobic conditions.

**Comment by jiuia** [comment]
@edkerk Hi! I have two questions about yeast8GEM working in anaerobic conditions: 1, what can I do to remove s_3714 from the reaction (r_4041)?  and  2, how do I change the biomass pseudoreaction reaction equation?  Looking forward to your reply!

**Comment by edkerk** [comment]
The function [code/otherChanges/anaerobicModel](https://github.com/SysBioChalmers/yeast-GEM/blob/main/code/otherChanges/anaerobicModel.m) can generate this "anaerobic model". If you only interested to remove `s_3714` from `r_4598` (the biomass reactions have been reconfigured, such that cofactors like heme are in their own pseudoreaction), you can modify the [respective lines](https://github.com/SysBioChalmers/yeast-GEM/blob/25d88c60b87cd0363980daf317da3ccd6ec1d87e/code/otherChanges/anaerobicModel.m#L21-L23).

**Comment by jiuia** [comment]
@edkerk    Thank you very much for your reply! May I ask which solver was used (cobra，raven or others)?  Because I keep getting errors when I run it in cobra's environment!

**Comment by jiuia** [comment]
@edkerk    like that  "Reference to a non-existent field 'rxns'.
Error setParam (line 49):index=find(strcmp(rxnList{i},model.rxns),1);"

**Comment by edkerk** [comment]
@jiuia I suggest you open a [Discussion thread](https://github.com/SysBioChalmers/yeast-GEM/discussions/new?category=help) where you explain exactly what commands you ran and what error message you observed. Your error message from `setParam` suggest that the model is not correctly loaded.

**Comment by jiuia** [comment]
@edkerk  ok fine!

**Comment by edkerk** [comment]
Work on an updated anaerobic model are discussed in #352
