### ISSUE TITLE
Question about ferredoxin iron-sulfur cluster

### ISSUE THREAD

**Issue by katajar** [SysBioChalmers/yeast-GEM#292]
Hello,
I'd like to add to the model new reactions from other organisms which includes oxidized/reduced form of ferredoxin [iron-sulfur] cluster.  Is it possible to expand reaction r_4325 to include those metabolites? I have no idea how to connect those reactions to the model. Are those clusters generic metabolites which are not necessary to include in the model?

**Comment by edkerk** [comment]
These reactions are indeed not connected to the main metabolic network that is active during FBA simulations. For one, it's a generic reaction, without specifying exact reactants (_which_ protein is the reaction acting on?), while the products are also not included in the biomass reaction.

Instead, I suggest you have a look at [this effort](https://www.sciencedirect.com/science/article/pii/S2589004221012633), where the yeast-GEM model was expanded to, among others, specifically include descriptions of iron-sulfur clusters and their inclusion in proteins, although this was focused on mitochondria. Some of these reactions we intend to also implement in yeast-GEM directly (#12).

**Comment by katajar** [comment]
@edkerk Thank you very much for the reply. I noticed that the problem is more complicated than I previously imagined. I tried to simulate the MitoYeast model but I didn't get flux values of ethanol and glycerol. Am I missing something or the model is especially focused on mitochondria?

**Comment by edkerk** [comment]
@katajar I suggest you directly post your issues with the MitoYeast model on that GitHub page, and make sure you clarify what you exactly did (which MATLAB commands etc.), to replicate your simulation and troubleshoot.
