### ISSUE TITLE
Feat-Polyphosphate metabolism

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/yeast-GEM#295]
### Description of the issue:
* Gapfilling in polyphosphate metabolism

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by edkerk** [comment]
Included in #339
