### ISSUE TITLE
feat: metSMILES annotation

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/yeast-GEM#318]
### Description of the issue:
This information is already retained in COBRA-style models, and would be valuable to also be kept here (and have RAVEN support the I/O of this annotation). As SMILES is not a identifiers.org annotation, it should rather be stored in a `model.metSmiles` (or `metSMILES`? Let's follow COBRA's style) field. SMILES are for instance useful when using a model in DLKcat.

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by hongzhonglu** [comment]
Good idea.  metSMILES seems better.
