### ISSUE TITLE
feat: Uniprot annotations for all genes

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/yeast-GEM#320]
### Description of the issue:
Add Uniprot annotations in `model.geneMiriams` (see [identifiers.org](https://registry.identifiers.org/registry/uniprot)) for all genes. Use the S288c reference [proteome](https://www.uniprot.org/proteomes/UP000002311) as source, providing one Uniprot ID per gene.

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by hongzhonglu** [comment]
Hi Ed, what is detailed annotation, only the Uniprot ID?

**Comment by hongzhonglu** [comment]
I see. It looks great.

**Comment by cheng-yu-zhang** [comment]
> Indeed, this has recently been done nicely for new genes that @cheng-yu-zhang has been introducing ([example](https://github.com/SysBioChalmers/yeast-GEM/blob/63e1de01e2881d3fcf384984e8ab07d870c980ac/data/modelCuration/complexAnnotation/complexAnnotationGenes.tsv), uniprot column), having this for all genes would be useful, particular with ec-models in mind.
I will think about it recently.
