### ISSUE TITLE
some memote workflows are failing

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/yeast-GEM#327]
### Description of the issue:

Some GH workflows that run memote-related tasks are failing: 
- https://github.com/SysBioChalmers/yeast-GEM/actions/workflows/memote-history.yml
- https://github.com/SysBioChalmers/yeast-GEM/actions/workflows/memote_release.yml

Also, the memote history report seems to have been showing 0 scores for a while:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/23480589/190955133-3a2bcca6-0f01-4a6a-ad03-927bfee099ed.png">

**Comment by edkerk** [comment]
Workflows that end with committing a file ([`memote_release`](https://github.com/SysBioChalmers/yeast-GEM/blob/3be6d1cb4e65e7245ed58acca904b8222a3abae1/.github/workflows/memote_release.yml) and [`memote-history`](https://github.com/SysBioChalmers/yeast-GEM/blob/3be6d1cb4e65e7245ed58acca904b8222a3abae1/.github/workflows/memote-history.yml)) occassionally fail at that last step. This seems to be related to multiple workflows running simultaneously. Rerunning a failed workflow (one at a time) results in a complete run.

In comparison, [`yaml-validation`](https://github.com/SysBioChalmers/yeast-GEM/blob/3be6d1cb4e65e7245ed58acca904b8222a3abae1/.github/workflows/yaml-validation.yml) and [`memote-run`](https://github.com/SysBioChalmers/yeast-GEM/blob/3be6d1cb4e65e7245ed58acca904b8222a3abae1/.github/workflows/memote-run.yml) do not commit any files and "never" fails (only if the yaml is not validated or memote errors).

I do not know how to fix this, perhaps we should not run multiple workflows at the same time?

Regarding the history report, I do not understand why this is. I also don't understand exactly how this function works (should it not construct a database with previous test results?).

**Comment by mihai-sysbio** [comment]
The history report is the same locally for me (0%) for the same memote `0.13.0`, so I guess the bug is upstream. For reference, I am encountering the following bug:
```
Loading result from '454f3bfe9382f092e863530f69dd4e04423e2f6d'.
/usr/local/lib/python3.9/site-packages/memote/suite/results/sql_result_manager.py:93: SAWarning: TypeDecorator BJSON() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  self.session.query(Result.memote_result)
error: Could not load result '454f3bfe9382f092e863530f69dd4e04423e2f6d'.
Loading result from 'e5f02acdced50cde19c7282b232aae73838e31a0'.
```

This is followed by a large number of commits for which results cannot be loaded. That being said, these commits are very old (newest are at the top), so I would expect that these failures don't matter.

> Rerunning a failed workflow (one at a time) results in a complete run.

It looks indeed like this is the case. Perhaps then the workflows should be merged and an `if` condition added to run the `release` report only if the target branch of the PR is `main`.
