### ISSUE TITLE
bug:spelling error for r_1024 "enxyme"

### ISSUE THREAD

**Issue by BjornFJohansson** [SysBioChalmers/yeast-GEM#354]
See "enxyme" in `model/yeast-GEM.yml`:

        - id: "r_1024"
        - name: "sucrose hydrolyzing enxyme"
        - metabolites: !!omap
            - s_0554: 1
            - s_0565: 1
            - s_0805: -1
            - s_1466: -1
        - lower_bound: 0
        - upper_bound: 1000
        - gene_reaction_rule: "YIL162W"
        - eccodes: "3.2.1.26"
        - subsystem:
            - "Starch and sucrose metabolism"

**Comment by mihai-sysbio** [comment]
@BjornFJohansson thanks for reporting this. If you feel up for it, we would be happy to take in a pull request. There are [Contributor guidelines](https://github.com/SysBioChalmers/yeast-GEM/blob/main/.github/CONTRIBUTING.md) available; let us know if you spot anything unexpected there.

**Comment by edkerk** [comment]
I'll include it in the next PR.
