### ISSUE TITLE
reactions r_0533, r_0534, r_0535 appear not balanced

### ISSUE THREAD

**Issue by charamon** [SysBioChalmers/yeast-GEM#358]
Hi !

I thnk these reactions are not balanced : one should remove the H+ in the right hand side of the reactions r_0533, r_0534 and r_0535. 

Best

**Comment by edkerk** [comment]
Below are the chemical formulas and charges of metabolites involved in `r_0534` (hexokinase):

Metabolite | Formula | Charge
-- | -- | --
ADP[c] | C10H12N5O10P2 | -3
ATP[c] | C10H12N5O13P3 | -4
D-glucose[c] | C6H12O6 | 0
D-glucose 6-phosphate[c] | C6H11O9P | -2
H+[c] | H | 1

This information can be gathered via e.g.

```matlab
metIdx = getIndexes(model,{'ADP[c]','ATP[c]','D-glucose[c]','D-glucose 6-phosphate[c]','H+[c]'},'metcomps');
model.metFormulas(metIdx)
model.metCharges(metIdx)
```

Note that the metabolites are protonated to physiological pH of 7, as is also done in e.g. [MetaCyc](https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=GLUCOKIN-RXN) (in contrast to [KEGG](https://www.genome.jp/entry/R00760)). The same holds true for `r_0533` and `r_0535`.

**Comment by IndrekM80** [comment]
Reaction r_4196 is missing NAD on the other side altogether :)

NADH[erm] + 2 Ferricytochrome b5[erm] <=> H+[erm] + 2 Ferrocytochrome b5[erm]
