### ISSUE TITLE
Hardware suggestion

### ISSUE THREAD

**Issue by Danyang95** [SysBioChalmers/yeast-GEM#366]
Hi Team,
Could you please provide any suggestions on hardware for running the model locally? For example, I am looking for the volume of RAM, GPU, disk and the CPU model.

Thanks for your help in advance.

**Comment by edkerk** [comment]
It very much depends on what type of analyses you want to perform and what software you use. Basic FBA can be run on basically any computer. If your analysis requires repeated FBAs, then it is mostly CPU that affects the speed of simulations.
