### ISSUE TITLE
non-working BioStudies URL in yeast9 paper

### ISSUE THREAD

**Issue by egonw** [SysBioChalmers/yeast-GEM#370]
I guess if I report it here, I get a quicker reply than when I post on PubPeer. I was scanning the paper and was looking for the data (and see if someone coud use it to update WikiPathways) and ran into the link to BioStudies:

![image](https://github.com/user-attachments/assets/f2c21b23-065f-47cb-a359-ac2f49cb86c2)

But the link (https://www.ebi.ac.uk/biostudies/sourcedata/studies/S-SCDT-10_1038-S44320-024-00060-7, PS, awesome use of compact identifiers!) gives me a 404:

![image](https://github.com/user-attachments/assets/ec5ae878-a899-4433-bbc3-2cac9f22b7f4)

And thanks for this important biocuration work!

**Comment by edkerk** [comment]
It would indeed be interesting to see if our work can update WikiPathways. We actually did not submit any data to BioStudies, it was Mol Syst Biol / EMBO / NatureSpringer who added that link. I'll contact the journal to find out what's their intention.

(Posting on GitHub will certainly result in the quickest response!)

**Comment by mihai-sysbio** [comment]
This appears to have been resolved - the BioStudies link works https://www.ebi.ac.uk/biostudies/sourcedata/studies/S-SCDT-10_1038-S44320-024-00060-7 
@egonw what would be required for an update in WikiPathways?

**Comment by egonw** [comment]
> @egonw what would be required for an update in WikiPathways?

Access was the first. The data will like idetifiers, and the number that can and cannot be mapped to yeast pathways we have can be looked into (to be honest, I forgot the context I had in mind at the time :/ ).

Thanks for fixing the link to the data!
