### ISSUE TITLE
feat: new reactions based on latest gene annotation

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/yeast-GEM#38]
@edkerk @BenjaSanchez , Dear both, in next phase, I want to focus on adding new GPRs into model. The followed is the detailed step:
1) Add new GPRs by merge of ise926, yeast7.6 and ito980;
2) Add new GPRs based on the yeast models and gene annotation in reactome, biocyc ,kegg, SGD and uniprotKB;

**Comment by BenjaSanchez** [comment]
update: PR #142 added all new rxns to `devel` based on annotation from 5 different databases. This issue will hence be closed on the next release.

**Comment by edkerk** [comment]
Solved in Yeast8
