### ISSUE TITLE
Add gene annotation for aminophospholipid transport in model

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/yeast-GEM#87]
@edkerk @BenjaSanchez @feiranl 
**Recently, we check the new GPRs from database, we have got the followed reaction:
phospholipid (in) + ATP + H20 <=> phospholipid (out) + ADP + phosphate + H+ 
YMR162C,  YAL026C, YER166W, YIL048W, YDR093W**

So based on the annotation of above genes, the phospholipid could be  phosphatidylserine (PS), phosphatidylethanolamine (PE) and phosphatidylcholine (PC),

In our present model, there are a lot of transport reactions about these three metabolites, like:

phosphatidyl-L-serine   (1-16:0, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:0,   2-16:1) [Golgi membrane]
phosphatidyl-L-serine   (1-16:1, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:1,   2-16:1) [Golgi membrane]
phosphatidyl-L-serine   (1-18:0, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:0,   2-16:1) [Golgi membrane]
phosphatidyl-L-serine   (1-18:1, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:1,   2-16:1) [Golgi membrane]
phosphatidyl-L-serine   (1-16:0, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:0,   2-18:1) [Golgi membrane]
phosphatidyl-L-serine   (1-16:1, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:1,   2-18:1) [Golgi membrane]
phosphatidyl-L-serine   (1-18:0, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:0,   2-18:1) [Golgi membrane]
phosphatidyl-L-serine   (1-18:1, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:1,   2-18:1) [Golgi membrane]

**According to the gene annotation, these reactions should be changed and the ATP should be put in the reactions. 
The question is that the similar reaction is more in our model. If we change one, the others will be also changed in reactions formula though the compartment lacks gene annotation evidence. How do we handle this condition ?** 

phosphatidyl-L-serine (1-16:0, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:0, 2-16:1) [vacuolar membrane]
phosphatidyl-L-serine (1-16:1, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:1, 2-16:1) [vacuolar membrane]
phosphatidyl-L-serine (1-18:0, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:0, 2-16:1) [vacuolar membrane]
phosphatidyl-L-serine (1-18:1, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:1, 2-16:1) [vacuolar membrane]
phosphatidyl-L-serine (1-16:0, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:0, 2-18:1) [vacuolar membrane]
phosphatidyl-L-serine (1-16:1, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:1, 2-18:1) [vacuolar membrane]
phosphatidyl-L-serine (1-18:0, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:0, 2-18:1) [vacuolar membrane]
phosphatidyl-L-serine (1-18:1, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:1, 2-18:1) [vacuolar membrane]

phosphatidyl-L-serine   (1-16:0, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:0,   2-16:1) [cell envelope]
phosphatidyl-L-serine   (1-16:1, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:1,   2-16:1) [cell envelope]
phosphatidyl-L-serine   (1-18:0, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:0,   2-16:1) [cell envelope]
phosphatidyl-L-serine   (1-18:1, 2-16:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:1,   2-16:1) [cell envelope]
phosphatidyl-L-serine   (1-16:0, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:0,   2-18:1) [cell envelope]
phosphatidyl-L-serine   (1-16:1, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-16:1,   2-18:1) [cell envelope]
phosphatidyl-L-serine   (1-18:0, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:0,   2-18:1) [cell envelope]
phosphatidyl-L-serine   (1-18:1, 2-18:1) [endoplasmic reticulum membrane]  <=> phosphatidyl-L-serine (1-18:1,   2-18:1) [cell envelope]

**Comment by BenjaSanchez** [comment]
will close this for now. Can be reopen if ever addressed.
