### ISSUE TITLE
fix: inter-OS issues

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#96]
### Description of the issue:
When switching between MAC and Windows machines to save the model, stoichiometric coefficients that use scientific notation are stored differently in the `.xml` file: MAC stores them as, e.g., `6e-05`, but Windows stores them as `6e-005`. This creates unnecesary changes in the `.xml` file when diffing (example [here](https://github.com/SysBioChalmers/yeast-GEM/commit/6e715e53fd90d8635d8cde369134e327423131cc)), eventhough the `.txt` file (and now also the `.yml` file) remain the same. We could adapt `saveYeastModel()` to fix this after calling `writeCbModel()`, but maybe there is a better way... @tpfau do you know if this is due to COBRA toolbox or libSBML? As the `.txt` file remains the same I would think it's due to the latter. Would there be in either case an easy fix?

#### Example:
Trying an IO cycle in Windows and MAC:
```matlab
model = loadYeastModel;
saveYeastModel(model);
```

**I hereby confirm that I have:**
- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/YeastMetabolicNetwork-GEM#required-software) for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/YeastMetabolicNetwork-GEM) about the issue

**Comment by tpfau** [comment]
@BenjaSanchez 
If its stoichiometric coefficients, than it is likely not in COBRA, as those are passed (as is) into OutputSBML.
However, this is also not necessarily due to libsbml, if this is some OS convention on number representation and libsbml uses a fixed output routine that gives different results on mac vs Windows. 
Maybe @skeating knows something here, as I have never noticed this behaviour.

**Comment by BenjaSanchez** [comment]
update: PR #117 modifies `saveYeastModel.m` to process the `.xml` file after `writeCbModel.m`. Definitively not optimal, but the only solution available on our side. This issue will be closed on the next release.

**Comment by tpfau** [comment]
@BenjaSanchez 
Do you by chance have a mac and a non-mac mat file of the model that goes into `writeCbModel`?
Just to see if there might be something off before it goes into the saving routine.

**Comment by BenjaSanchez** [comment]
@tpfau I only have windows-generated `.mat` files, but in [GECKO](https://github.com/SysBioChalmers/GECKO/pull/29) we also had to address this issue, and there we are always saving from the same `.mat` structure both in windows and MAC, which makes me think that this is an issue with writing, not reading. Furthermore, below a screenshot on the matrix format with a windows machine, which is the same as the MAC format, however it is when saving that this changes in windows:
![image](https://user-images.githubusercontent.com/9384349/40708961-10ca277e-63f5-11e8-9351-222513a98f89.png)

If you want to do further analysis, the `.mat` in `master` is generated with windows, and if you load the `.xml` with MAC you get the other one. If you don't have a MAC machine maybe @hongzhonglu can assist?

**Comment by tpfau** [comment]
I can reproduce this issue on win (00X) vs linux (0X)
Personally, I would not fix this manually but wait for a fix from the SBML crew. The fix you currently have could well kill some annotations that have a format `-00whatever`. So I would suggest to leave this open until a libsbml patch is available.
I'll contact @skeating about it, maybe she can identify where this is going wrong.

**Comment by tpfau** [comment]
I would suggest to use `regexprep` instead of `strrep` and test for the `-` sign instead of only changing those with one. I know, it is highly unlikely, that you will have large numbers in there, but it could happen.
```Matlab
        if length(regexp(inline,'[0-9]e-?00[0-9]')) == 1 && length(regexp(inline,'e-?00')) == 1
            inline = regexprep(inline,'(?<=[0-9]e-?)00(?=[0-9])','0');
        end
```
You could even check for the stoichiometry tag, to ensure, that this really only happens with stoichiometries (and thereby skipping the first regexp checks):
```Matlab
            inline = regexprep(inline,'(?<=stoichiometry="[0-9]+(\.[0-9]+)?e-?)00(?=[0-9])','0');
```
